# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Seungmin Park
title: Computer Science Student
email: psm0811@kyonggi.ac.kr
website: https://smpark00.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: sm_park00
github_username:  smpark00
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sm_park0.0
linkedin_username: seungmin-park-7405652a9
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! My name is Seungmin Park, and I'm currently in my final semester at Kyonggi University. I'm passionate about <mark>AI</mark> and <mark>Data science</mark>, and I’ve had the opportunity to work on a variety of projects in these fields. I'm a fast and motivated learner, always ready to dive into new challenges. Right now, I'm gaining practical experience as a Data Analyst intern at <mark>PathoBrainSeq</mark>, a startup company based in the United States.

  Currently, I am most focusing on: <mark>Data visualization</mark> and <mark>Machine Learning</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kyonggi University
        caption: 2019.03 - 2025.08 (Expected)
        sub_title: B.S. Computer Engineering
        description: |
          At Kyonggi University, I made the most of every opportunity to grow as a student and leader:
          
          - <mark>SW-Centered University Ambassador</mark>: Top beneficiary of Kyonggi University SW-Centered program. I completed 4 international software training programs. (3 USA, 1 Singapore)
          
          - <mark>International Presenter</mark>: Represented our SW-Centered program when the Philippine Presidential Office’s Commission on Higher Education.
          
          - <mark>Influence</mark>: Successfully pitched the establishment of a Mobility department to the university president.

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PathoBrainSeq
        link: https://www.pathobrainseq.com/
        sub_title: Data Analyst Intern
        caption: 2025.02 - Present
        quote: >
          Solving 21st-century medical puzzles by decoding genomic data for precise Alzheimer’s diagnosis.
        description: | # this will include new lines to allow paragraphs
          Under a strict NDA, I can’t share detailed specifics, but my role focuses on analyzing genetic datasets, creating interactive visualizations, and extracting actionable insights to drive Alzheimer’s research and diagnostics.


  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Software Engineering Lab
        sub_title: Undergraduate Researcher
        caption: 2024.10 - 2025.02
        link: https://sites.google.com/view/safetysw
        link_text: Kyonggi University SELAB
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      
      - layout: left
        title: Purdue University
        # link_text: boringcompany.com
        sub_title: Visiting Scholar
        caption: 2024.03 - 2024.06
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
